services:
  database:
    image: "postgres:17"
    environment:
      POSTGRES_USER: "administrator"
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: "uniflitzer"
    ports:
      - "5432:5432"
    volumes:
      - "database-data:/var/lib/postgresql/data"

  application:
    image: "ghcr.io/stevensolleder/uniflitzerbackend:latest"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/uniflitzer"
      SPRING_DATASOURCE_USERNAME: "administrator"
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
    ports:
      - "8080:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=300
      - REPO_USER=username
      - REPO_PASS=password
    restart: unless-stopped

volumes:
  database-data: